when:
  - event: [push, pull_request]
    branch: master

steps:
  - name: test
    image: ghcr.io/eliminyro/ci-tool:latest
    pull: true
    commands:
      - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      - go test -race -tags=integration ./...

  - name: fmt
    image: ghcr.io/eliminyro/ci-tool:latest
    pull: true
    commands:
      - gofmt -w .
      - git diff --exit-code HEAD
    depends_on: []

  - name: lint
    image: ghcr.io/eliminyro/ci-tool:latest
    pull: true
    commands:
      - golangci-lint run
    depends_on: []

  - name: auto-merge
    image: ghcr.io/eliminyro/ci-tool:latest
    pull: true
    environment:
      GH_TOKEN:
        from_secret: gh_repo_token
    commands:
      - ci auto-merge
    depends_on:
      - test
      - fmt
      - lint
    when:
      - event: pull_request
