when:
  - event: [push, pull_request]
    branch: master

steps:
  - name: test
    image: ghcr.io/eliminyro/go-ci:latest
    commands:
      - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      - go test -race -tags=integration ./...

  - name: fmt
    image: ghcr.io/eliminyro/go-ci:latest
    commands:
      - gofmt -w .
      - git diff --exit-code HEAD
    depends_on: []

  - name: lint
    image: ghcr.io/eliminyro/go-ci:latest
    commands:
      - golangci-lint run
    depends_on: []

  - name: auto-merge
    image: curlimages/curl
    environment:
      GH_TOKEN:
        from_secret: gh_repo_token
    commands:
      - 'curl -sf -X PUT -H "Authorization: token $GH_TOKEN" -H "Accept: application/vnd.github+json" "https://api.github.com/repos/$CI_REPO/pulls/$CI_COMMIT_PULL_REQUEST/merge" -d "{\"merge_method\":\"squash\"}"'
    depends_on:
      - test
      - fmt
      - lint
    when:
      - event: pull_request
